"""Add tool_data to chat messages

Revision ID: b9cce7e14685
Revises: 10c568b2cca2
Create Date: 2026-05-16 12:52:18.600233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cce7e14685'
down_revision: Union[str, Sequence[str], None] = '10c568b2cca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tool_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tool_data')
    # ### end Alembic commands ###
