"""Add tool_name to chat messages

Revision ID: db94777afdea
Revises: b9cce7e14685
Create Date: 2026-05-16 13:25:15.118350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db94777afdea'
down_revision: Union[str, Sequence[str], None] = 'b9cce7e14685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tool_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tool_name')
    # ### end Alembic commands ###
